# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MjUi.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MjUi(object):
    def setupUi(self, MjUi):
        MjUi.setObjectName("MjUi")
        MjUi.resize(701, 884)
        self.label = QtWidgets.QLabel(MjUi)
        self.label.setGeometry(QtCore.QRect(0, 120, 701, 600))
        self.label.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.label.setAutoFillBackground(False)
        self.label.setStyleSheet("")
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("lib/face.gif"))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(MjUi)
        self.label_2.setGeometry(QtCore.QRect(0, 0, 701, 121))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("lib/logo.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(MjUi)
        self.label_3.setGeometry(QtCore.QRect(-20, 710, 721, 151))
        self.label_3.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.pushButton = QtWidgets.QPushButton(MjUi)
        self.pushButton.setGeometry(QtCore.QRect(510, 740, 161, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("QPushButton{\n"
"    background-color: rgb(0, 255, 17);\n"
"    border-radius:25px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    \n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    \n"
"    \n"
"    color: rgb(5, 213, 75);\n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(MjUi)
        self.pushButton_2.setGeometry(QtCore.QRect(510, 800, 161, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("QPushButton{\n"
"    \n"
"    background-color: rgb(255, 0, 0);\n"
"    border-radius:25px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    \n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    \n"
"    color: rgb(255, 75, 75);\n"
"}")
        self.pushButton_2.setObjectName("pushButton_2")
        self.textBrowser = QtWidgets.QTextBrowser(MjUi)
        self.textBrowser.setGeometry(QtCore.QRect(10, 711, 491, 141))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.textBrowser.setFont(font)
        self.textBrowser.setStyleSheet("background: transparent;\n"
"border-radius:none;\n"
"color:white;\n"
"font-size:14px;")
        self.textBrowser.setObjectName("textBrowser")
        self.label_4 = QtWidgets.QLabel(MjUi)
        self.label_4.setGeometry(QtCore.QRect(0, 860, 701, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_4.setObjectName("label_4")

        self.retranslateUi(MjUi)
        QtCore.QMetaObject.connectSlotsByName(MjUi)

    def retranslateUi(self, MjUi):
        _translate = QtCore.QCoreApplication.translate
        MjUi.setWindowTitle(_translate("MjUi", "Form"))
        self.pushButton.setText(_translate("MjUi", "Start"))
        self.pushButton_2.setText(_translate("MjUi", "Terminate"))
        self.label_4.setText(_translate("MjUi", "                                                            @Abhijit Gupta"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MjUi = QtWidgets.QWidget()
    ui = Ui_MjUi()
    ui.setupUi(MjUi)
    MjUi.show()
    sys.exit(app.exec_())
